name: Infrastructure provisions
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
permissions:
  contents: read
  id-token: write
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configuration the Aws Cred
        uses: aws-action/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::376129850044:role/provision-infra
          aws-region: ap-southeast-1
          role-session-name: github-svc-tf-infra
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_version: 1.6.3
      - name: Terraform init
        run: terraform init
        working-directory: app.tf/
      - name: Terraform plan
        run: terraform plan
        working-directory: app.tf/
      - name: Terraform apply
        run: terraform apply
        working-directory: app.tf/
          