name: Terraform destroy

on:
  workflow_dispatch:
    inputs:
        confirmation:
            description: 'Type "Confirm" to destroy all terraform'
            required: true
            default: ''
            
permissions:
  contents: read
  id-token: write

jobs:
  destroy:
    runs-on: ubuntu-latest
    enviroment: ${{ github.ref_name }}
    steps: 
      - name: Checkout 
        uses: actions/checkout@v4
      
      - name: Configuration the AWS Credential 
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::376129850044:role/provision-infra
          aws-region: ap-southeast-1
          role-session-name: provision-infra
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_version: 1.6.3
      - name: Terraform init
        run: terraform init -backend-config="key=github_ci/infra/${{ github.ref_name }}-provision.tfstate"
  
      - name: Terraform destroy plan
        if: ${{ inputs.confirmation = 'Confirm' }}
        run: terraform plan -destroy -var-file=envtfvars/${{ github.ref_name }}.tfvars
          
      - name: Terraform destroy
        if: ${{ inputs.confirmation = 'Confirm' }}
        run: terraform destroy -auto-approve -var-file=envtfvars/${{ github.ref_name }}.tfvars
          
      - name: Check Confirmation
        if: github.event.inputs.confirmation != 'Confirm'
        run: |
            echo "not provided"
            exit 1