name: Infrastructure provisions
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
permissions:
  contents: read
  id-token: write
jobs:
  
  validating_tf:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Run Terrascan
        id: terrascan
        uses: tenable/terrascan-action@main
        with:
          iac_type: 'terraform'
          iac_version: 'v14'
          policy_type: 'aws'
          only_warn: true
          sarif_upload: true
         
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: terrascan.sarif
          
  terraform:
    runs-on: ubuntu-latest
    if: always()
    needs: [validating_tf]
    environment: ${{ github.ref_name }} 
    steps: 
      - name: Checkout 
        uses: actions/checkout@v4
      
      - name: Configuration the AWS Credential 
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::376129850044:role/provision-infra
          aws-region: ap-southeast-1
          role-session-name: provision-infra
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
            cli_version: 1.6.3
      - name: Terraform init
        run: terraform init
  
      - name: Terraform plan for prod environment 
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform plan -var-file=envtfvars/main.tfvars
          
      - name: Terraform plan for dev environment 
        if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
        run: terraform plan -var-file=envtfvars/dev.tfvars
  
      - name: Terraform apply for prod environment 
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve -var-file=envtfvars/main.tfvars
          
      - name: Terraform apply for dev environment 
        if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
        run: terraform apply -auto-approve -var-file=envtfvars/dev.tfvars


    # Docker Build and push
#   docker:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Login to Docker Hub
#         uses: docker/login-action@v3
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}
#       -
#         name: Set up QEMU
#         uses: docker/setup-qemu-action@v3
#       -
#         name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v3
#       -
#         name: Build and push
#         uses: docker/build-push-action@v6
#         with:
#           push: true
#           tags: user/app:latest